Repository YHJ96/pre-project-setting-practice, pull requests merged in 2022-08, with the labels that each got.

#2 docs: Git Commit Message 추가 완료
  README.md
Labels: 📃 문서

#3 docs: REPORT_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: ⚙ 설정, 📃 문서

#4 feat: webpack 초기 설정 완료
  .gitignore
  LICENSE
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/App.module.css
  frontend/src/index.css
  frontend/src/index.html
  frontend/src/index.js
  frontend/webpack.config.js
Labels: ⚙ 설정, 📱 FE, 📃 문서

#15 build.gradle, application.yml: REST Docs, JPA, Security 설정 추가
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ 설정, 🖥 BE

#18 2.x 요구사항 중 중요도 상 API 문서화
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/pre_38/pre_project/PreProjectApplication.java
  src/main/java/com/pre_38/pre_project/dto/MultiResponseDto.java
  src/main/java/com/pre_38/pre_project/dto/PageInfo.java
  src/main/java/com/pre_38/pre_project/dto/SingleResponseDto.java
  src/main/java/com/pre_38/pre_project/member/entity/Member.java
  src/main/java/com/pre_38/pre_project/member/service/MemberService.java
  src/main/java/com/pre_38/pre_project/question/controller/QuestionController.java
  src/main/java/com/pre_38/pre_project/question/dto/QuestionDto.java
  src/main/java/com/pre_38/pre_project/question/entity/Question.java
  src/main/java/com/pre_38/pre_project/question/mapper/QuestionMapper.java
  src/main/java/com/pre_38/pre_project/question/service/QuestionService.java
  src/test/java/com/pre_38/pre_project/restdocs/question/QuestionControllerRestDocsTest.java
Labels: 🖥 BE

#17 API 문서화 진행 - DTO 클래스(ReplyDto.java), Entity 클래스(Reply.java) 설정 완료
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/pre-project-setting-practice.iml
  .idea/vcs.xml
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/pre_38/pre_project/PreProjectApplication.java
  backend/src/main/java/com/pre_38/pre_project/dto/MultiResponseDto.java
  backend/src/main/java/com/pre_38/pre_project/dto/PageInfo.java
  backend/src/main/java/com/pre_38/pre_project/dto/SingleResponseDto.java
  backend/src/main/java/com/pre_38/pre_project/reply/dto/ReplyDto.java
  backend/src/main/java/com/pre_38/pre_project/reply/entity/Reply.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/com/pre_38/pre_project/PreProjectApplicationTests.java
Labels: ⚙ 설정, 🖥 BE, 📃 문서

#21 2.1 요구사항에 2.6 페이지 관련 요구사항 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/pre_38/pre_project/dto/MultiResponseDto.java
  src/main/java/com/pre_38/pre_project/dto/PageInfo.java
  src/main/java/com/pre_38/pre_project/question/controller/QuestionController.java
  src/main/java/com/pre_38/pre_project/question/entity/Question.java
  src/main/java/com/pre_38/pre_project/question/service/QuestionService.java
  src/test/java/com/pre_38/pre_project/restdocs/question/QuestionControllerRestDocsTest.java
Labels: 🖥 BE, 📃 문서

#23 Member엔티티에 email필드 추가
  backend/src/main/java/com/pre_38/pre_project/member/entity/Member.java
  backend/src/test/java/com/pre_38/pre_project/restdocs/question/QuestionControllerRestDocsTest.java
Labels: ⚙ 설정, 🖥 BE, 📃 문서

#28 Feature/ds02168
  backend/src/main/java/com/pre_38/pre_project/audit/Auditable.java
  backend/src/main/java/com/pre_38/pre_project/member/entity/Member.java
  backend/src/main/java/com/pre_38/pre_project/question/controller/QuestionController.java
  backend/src/main/java/com/pre_38/pre_project/question/entity/Question.java
  backend/src/test/java/com/pre_38/pre_project/restdocs/question/QuestionControllerRestDocsTest.java
Labels: 🖥 BE

#30 김나율 임수인 유태형 병합
  PULL_RESQUEST_TEST.md
  REQUEST.md
  backend/src/main/java/com/pre_38/pre_project/audit/Auditable.java
  backend/src/main/java/com/pre_38/pre_project/member/controller/MemberController.java
  backend/src/main/java/com/pre_38/pre_project/member/dto/MemberLoginDto.java
  backend/src/main/java/com/pre_38/pre_project/member/dto/MemberSignupRequestDto.java
  backend/src/main/java/com/pre_38/pre_project/member/entity/Member.java
  backend/src/main/java/com/pre_38/pre_project/member/repository/MemberRepository.java
  backend/src/main/java/com/pre_38/pre_project/question/controller/QuestionController.java
  backend/src/main/java/com/pre_38/pre_project/question/entity/Question.java
  backend/src/main/java/com/pre_38/pre_project/reply/controller/ReplyController.java
  backend/src/main/java/com/pre_38/pre_project/reply/dto/ReplyDto.java
  backend/src/main/java/com/pre_38/pre_project/reply/entity/Reply.java
  backend/src/main/java/com/pre_38/pre_project/reply/mapper/ReplyMapper.java
  backend/src/main/java/com/pre_38/pre_project/reply/service/ReplyService.java
  backend/src/test/java/com/pre_38/pre_project/restdocs/question/QuestionControllerRestDocsTest.java
  backend/test_kal1777
Labels: 🖥 BE

#32 dev/be -> feature/ds02168
  backend/.idea/.gitignore
Labels: 🖥 BE
